### ISSUE TITLE
Trailing errors when using space in key

### ISSUE THREAD

**Issue by bpeschier** [lericson/pylibmc#114]
While debugging the Django tests I found that pylibmc's flush_all reports an error when you have just set a erroneous key with a space:

```
>>> c = pylibmc.Client(['127.0.0.1:11211',])
>>> c.set('test', 'value')
True
>>> c.flush_all()
True
>>> c.set('test with a space', 'value')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pylibmc.SocketCreateError: error 11 from memcached_set: SUCCESS
>>> c.flush_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pylibmc.SomeErrors: error 19 from flush_all: SUCCESS
>>> 
```

There seems to be a bit of lag in it, because after a short amount of time the flush will succeed.

This is on pylibmc 1.2.3 with libmemcached 1.0.15 and memcached 1.4.15

**Comment by edmorley** [comment]
Just checking I'm understanding this correctly:
* unlike python-memcached, pylibmc does not verify keys by default (due to the default libmemcached behaviour)
* key verification can be enabled by using the `verify_keys` behaviour option, but presumably has a performance impact, so it's common for people to not enable it
* if `verify_keys` in not enabled, using `.set('key with spaces', 'value')` results in the key being sent as-is to the server
* if the server receives such a key, it currently handles it poorly (if not using binary mode), causing subsequent commands to fail for a few seconds, when really it should have immediately returned a sensible error code, like happens for the "key too long" case

-> all of this means it's just a bug in memcached server, which pylibmc can't do anything about & that workarounds for the user are to either use `verify_keys` or else use binary mode

Is this correct?

Thanks :-)
